apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::905022813559:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-193TNR9NHLSCB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::905022813559:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-24T00:11:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1602"
  uid: 865acf45-58a3-40d3-94fe-cb6e9c895b23
